name: Mac Testing

on: [push]

env:
  FC: gfortran-9

jobs:
  build:
    runs-on: macos-10.15
    
    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
      with:
        path: 'clone_branch'

    - name: Is Gfortran installed?
      run: which gfortran-9

    - name: Checkout Baseline
      if: ${{ github.ref != 'develop' }}  # TODO: This is an insufficient check -- forks could use the develop branch
      uses: actions/checkout@v2
      with:
        repository: 'NREL/EnergyPlus'
        ref: 'develop'
        path: 'clone_baseline'
        fetch-depth: '1'

    - name: Checkout Regressions
      if: ${{ github.ref != 'develop' }}
      uses: actions/checkout@v2
      with:
        repository: 'NREL/EnergyPlusRegressionTool'
        ref: 'master'
        path: 'clone_regressions'
        fetch-depth: '1'

  # dependency installation will be adjusted when using self-hosted stuff and eventually docker containers
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install beautifulsoup4 soupsieve boto

    - name: Create Baseline Build Directory
      if: ${{ github.ref != 'develop' }}
      run: cmake -E make_directory ${{runner.workspace}}/clone_baseline/build

    - name: Configure Baseline
      if: ${{ github.ref != 'develop' }}
      shell: bash
      working-directory: ${{runner.workspace}}/clone_baseline/build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_FORTRAN=ON -DBUILD_TESTING:BOOL=ON -DCOMMIT_SHA=$COMMIT_SHA -DENABLE_GTEST_DEBUG_MODE:BOOL=OFF -DLINK_WITH_PYTHON=ON $GITHUB_WORKSPACE/clone_baseline

    - name: Build Baseline
      if: ${{ github.ref != 'develop' }}
      working-directory: ${{runner.workspace}}/clone_baseline/build
      shell: bash
      run: cmake --build . -j 2

    - name: Test Baseline
      if: ${{ github.ref != 'develop' }}
      working-directory: ${{runner.workspace}}/clone_baseline/build
      shell: bash
      run: ctest -R 1ZoneUncontrolled

    - name: Create Branch Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/clone_branch/build

    - name: Configure Branch without Regressions
      if: ${{ github.ref != 'develop' }}
      shell: bash
      working-directory: ${{runner.workspace}}/clone_branch/build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_FORTRAN=ON -DBUILD_TESTING:BOOL=ON -DENABLE_GTEST_DEBUG_MODE:BOOL=OFF -DLINK_WITH_PYTHON=ON ..

    - name: Configure Branch with Regressions
      if: ${{ github.ref != 'develop' }}
      shell: bash
      working-directory: ${{runner.workspace}}/clone_branch/build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_FORTRAN=ON -DBUILD_TESTING:BOOL=ON -DENABLE_REGRESSION_TESTING:BOOL=ON -DREGRESSION_BASELINE_PATH:PATH=${{runner.workspace}}/clone_baseline/build -DREGRESSION_SCRIPT_PATH:PATH=${{runner.workspace}}/clone_regressions/build -DREGRESSION_BASELINE_SHA:STRING=UNNKOWN_SHA -DCOMMIT_SHA=${{github.sha}} -DENABLE_GTEST_DEBUG_MODE:BOOL=OFF -DLINK_WITH_PYTHON=ON ..

    - name: Build Branch
      working-directory: ${{runner.workspace}}/clone_branch/build
      shell: bash
      run: cmake --build . -j 2

    - name: Test Branch
      working-directory: ${{runner.workspace}}/clone_branch/build
      shell: bash
      run: ctest -R 1ZoneUncontrolled
