name: Mac Release Build

on: [push]

env:
  FC: /usr/local/bin/gfortran-9
  # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: Install Brew dependencies
      run: brew cask install mactex

    - name: Check TeX binaries
      working-directory: /Library/TeX/texbin
      run: ls

    - name: Install IFW
      run: aqt tool mac tools_ifw 3.2.2 qt.tools.ifw.32 --outputdir=${{runner.workspace}}/Qt

    - name: Add IFW to PATH
      run: echo "::add-path::${{runner.workspace}}/Qt/Tools/QtInstallerFramework/3.2/bin"

    - name: Add TeX to PATH
      run: echo "::add-path::/Library/TeX/texbin"

    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DLINK_WITH_PYTHON=ON -DDOCUMENTATION_BUILD="BuildWithAll" -DTEX_INTERACTION="batchmode" -DBUILD_FORTRAN=ON -DBUILD_PACKAGE:BOOL=ON ..

    - name: Build Package
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      shell: bash
      run: cmake --build . --target package -j 2

    - name: Inspect build for package names
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      shell: bash
      run: ls

    - name: Upload Tarball
      uses: actions/upload-artifact@v2
      with:
        name: MacReleaseTarball
        path: ${{runner.workspace}}/EnergyPlus/build/EnergyPlus-*-Darwin-x86_64.tar.gz

    - name: Upload IFW Installer
      uses: actions/upload-artifact@v2
      with:
        name: MacReleaseIFW
        path: ${{runner.workspace}}/EnergyPlus/build/EnergyPlus-*-Darwin-x86_64.dmg
