name: clang-format

on:
  push:
    branches: [ develop ]
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ develop ]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        path:
          - 'src/EnergyPlus'
          - 'tst/EnergyPlus/unit'
    steps:
      - uses: actions/checkout@v2
      - name: Run clang-format style check for C/C++ programs.
        uses: jidicula/clang-format-action@v3.2.0
        with:
          clang-format-version: '10'
          check-path: ${{ matrix.path }}
