name: CMake

on: [push]

jobs:
  custom_check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Custom Check
      run: /bin/bash ${{runner.workspace}}/scripts/dev/custom_check.sh ${{runner.workspace}}
