name: Documentation Windows Debug

on: [push]

env:
  CMAKE_Fortran_COMPILER: "/c/msys64/mingw64/bin/x86_64-w64-mingw32-gfortran.exe"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - name: Checkout EnergyPlus
      uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install System dependencies and LaTeX
      shell: bash
      run: |
        set -x
        echo "Downloading MiKTeX CLI installer"
        # We download from a specific miror already # TODO: Should store this setup package somewhere ourselves
        curl -L -O https://ctan.math.illinois.edu/systems/win32/miktex/setup/windows-x64/miktexsetup-4.1-x64.zip
        unzip miktexsetup-4.1-x64.zip

        echo "Setting up the local package directory via download"
        ./miktexsetup_standalone --verbose \
            --local-package-repository=C:/ProgramData/MiKTeX-Repo \
            --remote-package-repository="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/" \
            --package-set=basic \
            download

        echo "Installing from the local package directory previously set up"
        ./miktexsetup_standalone --verbose \
            --local-package-repository=C:/ProgramData/MiKTeX-Repo \
            --package-set=basic \
            --shared \
            install

        echo "Adding MiKTeX bin folder to PATH and to GITHUB_PATH"
        echo "C:/Program Files/MiKTeX/miktex/bin/x64/" >> $GITHUB_PATH
        export PATH="/c/Program Files/MiKTeX/miktex/bin/x64/:$PATH"

        echo "Configuring MiKTeX to install missing packages on the fly"
        initexmf --admin --verbose --set-config-value='[MPM]AutoInstall=1'

        echo "Configure default mirror for packages"
        mpm --admin --set-repository="https://ctan.math.illinois.edu/systems/win32/miktex/tm/packages/"
        # Avoid annoying warning: "xelatex: major issue: So far, you have not checked for updates as a MiKTeX user."
        mpm --find-updates
        mpm --admin --find-updates

    - name: Create Build Directory
      run: cmake -E make_directory ./doc/build/

    - name: Configure CMake
      working-directory: ./doc/build
      shell: bash
      run: |
        set -x
        cmake -G "Visual Studio 16 2019" -A x64 \
              -DTEX_INTERACTION=batchmode -DDOCS_TESTING=ON ../

    - name: Add problem matcher
      run: echo "::add-matcher::.github/workflows/doc-problem-match.json"

    - name: Build Docs
      working-directory: ${{runner.workspace}}/EnergyPlus/doc/build
      run: cmake --build . -j 2  --config $BUILD_TYPE

    - name: Test InputOutputReference
      shell: bash
      working-directory: ./doc/build/pdf/
      run: |
        set -x
        pdfinfo InputOutputReference.pdf || true
        npages=$(pdfinfo InputOutputReference.pdf | /bin/grep "Pages:" | sed 's/[^0-9]*//')
        [ "$npages" -le "2800" ] && echo "TOC is missing" && exit 1

    - name: Upload Acknowledgments
      uses: actions/upload-artifact@v2
      with:
        name: Acknowledgments
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/Acknowledgments.pdf

    - name: Upload AuxiliaryPrograms
      uses: actions/upload-artifact@v2
      with:
        name: AuxiliaryPrograms
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/AuxiliaryPrograms.pdf

    - name: Upload EMSApplicationGuide
      uses: actions/upload-artifact@v2
      with:
        name: EMSApplicationGuide
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/EMSApplicationGuide.pdf

    - name: Upload EnergyPlusEssentials
      uses: actions/upload-artifact@v2
      with:
        name: EnergyPlusEssentials
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/EnergyPlusEssentials.pdf

    - name: Upload EngineeringReference
      uses: actions/upload-artifact@v2
      with:
        name: EngineeringReference
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/EngineeringReference.pdf

    - name: Upload ExternalInterfacesApplicationGuide
      uses: actions/upload-artifact@v2
      with:
        name: ExternalInterfacesApplicationGuide
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/ExternalInterfacesApplicationGuide.pdf

    - name: Upload GettingStarted
      uses: actions/upload-artifact@v2
      with:
        name: GettingStarted
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/GettingStarted.pdf

    - name: Upload InputOutputReference
      uses: actions/upload-artifact@v2
      with:
        name: InputOutputReference
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/InputOutputReference.pdf

    - name: Upload InterfaceDeveloper
      uses: actions/upload-artifact@v2
      with:
        name: InterfaceDeveloper
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/InterfaceDeveloper.pdf

    - name: Upload ModuleDeveloper
      uses: actions/upload-artifact@v2
      with:
        name: ModuleDeveloper
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/ModuleDeveloper.pdf

    - name: Upload OutputDetailsAndExamples
      uses: actions/upload-artifact@v2
      with:
        name: OutputDetailsAndExamples
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/OutputDetailsAndExamples.pdf

    - name: Upload PlantApplicationGuide
      uses: actions/upload-artifact@v2
      with:
        name: PlantApplicationGuide
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/PlantApplicationGuide.pdf

    - name: Upload TipsAndTricksUsingEnergyPlus
      uses: actions/upload-artifact@v2
      with:
        name: TipsAndTricksUsingEnergyPlus
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/TipsAndTricksUsingEnergyPlus.pdf

    - name: Upload UsingEnergyPlusForCompliance
      uses: actions/upload-artifact@v2
      with:
        name: UsingEnergyPlusForCompliance
        path: ${{runner.workspace}}/EnergyPlus/doc/build/pdf/UsingEnergyPlusForCompliance.pdf
