name: Linux Release Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install LaTeX
      run: sudo apt-get install texlive texlive-xetex texlive-science

    # TODO: Install IFW from https://download.qt.io/official_releases/qt-installer-framework/3.2.2/

    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DCPACK_BINARY_IFW=OFF -DLINK_WITH_PYTHON=ON -DDOCUMENTATION_BUILD="BuildWithAll" -DTEX_INTERACTION="nonstopmode" -DBUILD_FORTRAN=ON -DBUILD_PACKAGE:BOOL=ON -DCOMMIT_SHA=DUMMYSHA ..

    - name: Build Package
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      shell: bash
      run: cmake --build . --target package -j 2

    - name: Inspect build for package names
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      shell: bash
      run: ls

#    - name: Upload Tarball
#      uses: actions/upload-artifact@v2
#      with:
#        name: LinuxRelease
#        path: ${{runner.workspace}}/EnergyPlus/build/*.tar.gz
