name: Linux Releases

on:
  push:
    tags:
      - '*'

jobs:
  linux_release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: Install APT dependencies
      run: sudo apt-get update && sudo apt-get install texlive texlive-xetex texlive-science libxkbcommon-x11-0 xorg-dev libgl1-mesa-dev

    - name: Install IFW
      run: aqt tool linux tools_ifw 3.2.2 qt.tools.ifw.32 --outputdir=${{runner.workspace}}/Qt

    - name: Add IFW to PATH
      run: echo "::add-path::${{runner.workspace}}/Qt/Tools/QtInstallerFramework/3.2/bin"

    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DLINK_WITH_PYTHON=ON -DDOCUMENTATION_BUILD="BuildWithAll" -DTEX_INTERACTION="batchmode" -DBUILD_FORTRAN=ON -DBUILD_PACKAGE:BOOL=ON ..

    - name: Build Package
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      shell: bash
      run: cmake --build . --target package -j 2

#    - name: Set Environment Variable Name of Linux Tarball Package
#      run: echo ::set-env name=PACKAGE_NAME_TAR::$(python3 ${{runner.workspace}}/EnergyPlus/scripts/dev/get_package_names.py ${{runner.workspace}}/EnergyPlus/build ubuntu18_tar)
#
#    - name: Temporary workaround to rename TAR package
#      run: cp "${{runner.workspace}}/EnergyPlus/build/$PACKAGE_NAME_TAR" "${{runner.workspace}}/EnergyPlus/build/${{ matrix.os }}_$PACKAGE_NAME_TAR"

    - name: Upload Tarball to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{runner.workspace}}/EnergyPlus/build/EnergyPlus-*-Linux-x86_64.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        asset_name: ${{ matrix.os }}_LinuxTarball

#    - name: Set Environment Variable Name of Linux IFW Installer Package
#      run: echo ::set-env name=PACKAGE_NAME_IFW::$(python3 ${{runner.workspace}}/EnergyPlus/scripts/dev/get_package_names.py ${{runner.workspace}}/EnergyPlus/build ubuntu18_run)
#
#    - name: Temporary workaround to rename IFW package
#      run: cp "${{runner.workspace}}/EnergyPlus/build/$PACKAGE_NAME_IFW" "${{runner.workspace}}/EnergyPlus/build/${{ matrix.os }}_$PACKAGE_NAME_IFW"

    - name: Upload IFW to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{runner.workspace}}/EnergyPlus/build/EnergyPlus-*-Linux-x86_64.run
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        asset_name: ${{ matrix.os }}_LinuxIFWInstaller

#    - name: Set Environment Variable Name of Linux Shell Installer Package
#      run: echo ::set-env name=PACKAGE_NAME_SH::$(python3 ${{runner.workspace}}/EnergyPlus/scripts/dev/get_package_names.py ${{runner.workspace}}/EnergyPlus/build ubuntu18_sh)
#
#    - name: Temporary workaround to rename SH package
#      run: cp "${{runner.workspace}}/EnergyPlus/build/$PACKAGE_NAME_SH" "${{runner.workspace}}/EnergyPlus/build/${{ matrix.os }}_$PACKAGE_NAME_SH"

    - name: Upload SH to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{runner.workspace}}/EnergyPlus/build/EnergyPlus-*-Linux-x86_64.sh
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        asset_name: ${{ matrix.os }}_LinuxShellInstaller
