name: Mac Build

on: [push]

jobs:
  python_no_psychcach:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
#
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DLINK_WITH_PYTHON=ON -DUSE_PSYCHROMETRICS_CACHING=OFF ..

    - name: Build EnergyPlus
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      shell: bash
      run: cmake --build . --target energyplus -j 2

  no_python_psychcach:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      #
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create Build Directory
        run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        run: cmake -DCMAKE_BUILD_TYPE=Release -DLINK_WITH_PYTHON=OFF -DUSE_PSYCHROMETRICS_CACHING=ON ..

      - name: Build EnergyPlus
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        shell: bash
        run: cmake --build . --target energyplus -j 2

  no_python_no_psychcach:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      #
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create Build Directory
        run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        run: cmake -DCMAKE_BUILD_TYPE=Release -DLINK_WITH_PYTHON=OFF -DUSE_PSYCHROMETRICS_CACHING=OFF ..

      - name: Build EnergyPlus
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        shell: bash
        run: cmake --build . --target energyplus -j 2

  no_glycol_cache:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      #
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create Build Directory
        run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        run: cmake -DCMAKE_BUILD_TYPE=Release -DUSE_GLYCOL_CACHING=OFF ..

      - name: Build EnergyPlus
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        shell: bash
        run: cmake --build . --target energyplus -j 2

  no_opengl:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      #
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create Build Directory
        run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        run: cmake -DCMAKE_BUILD_TYPE=Release -OPENGL_REQUIRED=OFF ..

      - name: Build EnergyPlus
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        shell: bash
        run: cmake --build . --target energyplus -j 2

  use_psych_stats:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      #
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create Build Directory
        run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        run: cmake -DCMAKE_BUILD_TYPE=Release -USE_PSYCH_STATS=ON ..

      - name: Build EnergyPlus
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        shell: bash
        run: cmake --build . --target energyplus -j 2

  no_use_psych_errors:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      #
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Create Build Directory
        run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        run: cmake -DCMAKE_BUILD_TYPE=Release -USE_PSYCH_ERRORS=OFF ..

      - name: Build EnergyPlus
        working-directory: ${{runner.workspace}}/EnergyPlus/build
        shell: bash
        run: cmake --build . --target energyplus -j 2
