name: Mac Releases

on:
  push:
    tags:
      - '*'

env:
  FC: /usr/local/bin/gfortran-9

jobs:
  mac_release:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: Install Brew dependencies
      run: brew cask install mactex

    - name: Check TeX binaries
      working-directory: /Library/TeX/texbin
      run: ls

    - name: Install IFW
      run: aqt tool mac tools_ifw 3.2.2 qt.tools.ifw.32 --outputdir=${{runner.workspace}}/Qt

    - name: Add IFW to PATH
      run: echo "::add-path::${{runner.workspace}}/Qt/Tools/QtInstallerFramework/3.2/bin"

    - name: Add TeX to PATH
      run: echo "::add-path::/Library/TeX/texbin"

    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: cmake -DCMAKE_BUILD_TYPE=Release -DLINK_WITH_PYTHON=ON -DDOCUMENTATION_BUILD="BuildWithAll" -DTEX_INTERACTION="batchmode" -DBUILD_FORTRAN=ON -DBUILD_PACKAGE:BOOL=ON ..

    - name: Build Package
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      shell: bash
      run: cmake --build . --target package -j 2

#    - name: Set Environment Variable Name of Mac Tarball Package
#      run: echo ::set-env name=PACKAGE_NAME_TAR::$(python3 ${{runner.workspace}}/EnergyPlus/scripts/dev/get_package_names.py ${{runner.workspace}}/EnergyPlus/build mac_tar)

    - name: Upload Tarball to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{runner.workspace}}/EnergyPlus/build/EnergyPlus-*-Darwin-x86_64.tar.gz
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        asset_name: MacTarball

#    - name: Set Environment Variable Name of Mac Installer Package
#      run: echo ::set-env name=PACKAGE_NAME_DMG::$(python3 ${{runner.workspace}}/EnergyPlus/scripts/dev/get_package_names.py ${{runner.workspace}}/EnergyPlus/build mac_dmg)

    - name: Upload DMG to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{runner.workspace}}/EnergyPlus/build/EnergyPlus-*-Darwin-x86_64.dmg
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
        asset_name: MacInstaller