name: Pull Request Labels

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check_pr_labels:
    runs-on: ubuntu-18.04

    steps:
    - name: Verify PR Labels
      uses: actions/verify-pr-label-action@v1.0.0
      with:
        github-token: '${{ secrets.GITHUB_TOKEN }}'
        valid-labels: 'Defect, Refactoring, NewFeature, Performance, DoNoPublish'
