name: Windows 64-bit Release Build

on: [push]

env:
  FC: C:\ProgramData\Chocolatey\bin\gfortran.exe

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: 'x64' # x64 or x86 (defaults to x64)

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install aqtinstall

    - name: Install Chocolately Packages
      run: choco install miktex && refreshenv

    - name: Look for LaTeX binaries
      working-directory: "C:\Program Files\MikTeX"
      run: dir

    - name: Add MikTeX binary folder to path
      run: echo "::add-path::/C/Program Files/MikTeX"

    - name: Install IFW
      run: aqt tool mac tools_ifw 3.2.2 qt.tools.ifw.32 --outputdir=${{runner.workspace}}/Qt

    - name: Add IFW to PATH
      run: echo "::add-path::${{runner.workspace}}/Qt/Tools/QtInstallerFramework/3.2/bin"

    - name: Also add assumed mingw bin directory to path
      run: echo "::add-path::/C/mingw64/bin"

    - name: Create Build Directory
      run: cmake -E make_directory ${{runner.workspace}}/EnergyPlus/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      run: cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release -DLINK_WITH_PYTHON=ON -DDOCUMENTATION_BUILD="BuildWithAll" -DTEX_INTERACTION="batchmode" -DBUILD_FORTRAN=ON -DBUILD_PACKAGE:BOOL=ON ..

    - name: Build Package
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      shell: bash
      run: cmake --build . --target package -j 2

    - name: Inspect build for package names
      working-directory: ${{runner.workspace}}/EnergyPlus/build
      shell: bash
      run: ls

    - name: Upload Zip Archive
      uses: actions/upload-artifact@v2
      with:
        name: LinuxReleaseTarball
        path: ${{runner.workspace}}/EnergyPlus/build/EnergyPlus-*-Windows-x86_64.zip

    - name: Upload IFW Installer
      uses: actions/upload-artifact@v2
      with:
        name: LinuxReleaseIFW
        path: ${{runner.workspace}}/EnergyPlus/build/EnergyPlus-*-Windows-x86_64.exe
